on: [push, pull_request]
name: Test and Build
jobs:
  test:
    if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
    strategy:
      matrix:
        go-version: [1.16.2]
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Generate protobuf
        shell: powershell
        run: .\scripts\proto.ps1
      - name: Test G14Manager
        run: go test ./...
      - name: Build Main G14Manager Binary
        run: go build -o build\G14Manager.exe .\cmd\manager
      - name: Build MatrixControl DLL (Release)
        run: MSBuild.exe .\cxx\MatrixController.sln /property:Configuration=Release /property:Platform=x64
      - name: Build MatrixControl DLL (Debug)
        run: MSBuild.exe .\cxx\MatrixController.sln /property:Configuration=Debug /property:Platform=x64
